"""added_documents_table

Revision ID: 48abc949ab7c
Revises: 8401c7f4ddba
Create Date: 2025-09-23 17:30:14.761571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48abc949ab7c'
down_revision: Union[str, Sequence[str], None] = '8401c7f4ddba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=150), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('expires_at', sa.BIGINT(), server_default=sa.text("(EXTRACT(EPOCH FROM (now() + interval '1 day')))::BIGINT"), nullable=False),
    sa.Column('max_downloads', sa.Integer(), server_default=sa.text('1000'), nullable=False),
    sa.Column('downloads_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('encrypted', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
